services:

  db:
    image: postgres:18.1-alpine3.22
    environment:
      POSTGRES_DB: Deribit-client
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8.4-alpine
    ports:
      - "6379:6379"

  app:
    build: .
    ports:
      - "8000:8000"

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

    environment:
      POSTGRES_DB: Deribit-client
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432

      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""

    command: >
      sh -c "
      python -m app.db.init_db &&
      uvicorn app.main:app --host 0.0.0.0 --port 8000
      "

  worker:
    build: .

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

    environment:
      POSTGRES_DB: Deribit-client
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432

      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""

    command: celery -A app.tasks.celery_tasks.celery worker --loglevel=info

  beat:
    build: .

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

    environment:
      POSTGRES_DB: Deribit-client
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: 5432

      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""

    command: celery -A app.tasks.celery_tasks.celery beat --loglevel=info

volumes:
  postgres_data: